### PR TITLE
Add basic RSS feed for Recent Uploads

### LINKED ISSUE #26: Enhancement: RSS Feed
It'd be neat to have an RSS/Atom feed of new documents.

### PR DESCRIPTION
**Pull request by cdzombak**
closes #26 

@steiza / @eby, what is the pathway to getting this reviewed/merged/deployed?

### CODE REVIEW

**Comment by eby** [comment]
Checked this out to https://qa.a2docs.org

As an aside had to install `python3-lxml` in order to install feedgen

Seems to be working ok @steiza @vielmetti

**Comment by cdzombak** [comment]
🎉 

Screen Shot 2019-09-11 at 5 03 35 PM

**Comment by eby** [comment]
I don't have merge permissions it seems but this seems good to go

**Comment by cdzombak** [comment]
> There's a few minor additional changes this inspires,

Indeed there are! Chief among them for me would be tracking upload times, not just dates; and reviewing the allowed HTML tags and refactoring some of the Bleach code, since there's some duplication there now (and the use of a global variable as a "constant," which, yuck).

> but we could land this as-is (or if you want to update this diff, that's fine too).

I'd prefer to land as-is, if only because I don't know when I'll have time/bandwidth to keep working on this.

**Comment by eby** [comment]
:ship: Deployed to production. Let me know if you notice anything.

**Comment by cdzombak** [comment]
> 🚢 Deployed to production. Let me know if you notice anything.

Awesome! Thanks, everyone 🍻

**Pull request merged**
